### ISSUE TITLE
Failing sample

### ISSUE THREAD

**Issue by pawelmhm** [Nykakin/chompjs#1]
Hello @Nykakin thanks for this wonderful library. Seems like I'm first person opening issue here. 

I started using library in my project and find it very useful, but I see one sample I'm having is not parsed correctly. It returns error. I created unit test to reproduce this issue here: 

https://github.com/Nykakin/chompjs/compare/master...pawelmhm:failing-sample?expand=1

Running this test in my localhost with Python 3.7.3 I get following:

```
ERROR: test_incorrect_escape (chompjs.test_parser.TestParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pawel/chompjs/chompjs/test_parser.py", line 121, in test_incorrect_escape
    result = parse_js_object(f.read())
  File "/home/pawel/chompjs/chompjs/chompjs.py", line 31, in parse_js_object
    return json.loads(parsed_json)
  File "/home/pawel/.pyenv/versions/3.7.3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/pawel/.pyenv/versions/3.7.3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/pawel/.pyenv/versions/3.7.3/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \uXXXX escape: line 1 column 7206 (char 7205)

----------------------------------------------------------------------
Ran 31 tests in 0.003s

FAILED (errors=1)
```

I see that other tool for parsing this kind of input works on it and produces valid dictionary.

**Comment by Nykakin** [comment]
Should be fixed by #2.
