### ISSUE TITLE
Fails for hexadecimal values

### ISSUE THREAD

**Issue by Nykakin** [Nykakin/chompjs#12]
The library doesn't support parsing hexadecimal values:

```python
>>> import chompjs
>>> chompjs.parse_js_object('{"test": 0x12}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mariusz/Documents/Projekty/chompjs/chompjs/chompjs.py", line 29, in parse_js_object
    raise ValueError("Parser error: ... {}".format(str(exception).encode('utf-8')))
ValueError: Parser error: ... b'12}'
```

**Comment by Nykakin** [comment]
Resolved since 1.1.0.
